#!/usr/bin/env bash
# This script loops indefinitely and reacts to SIGTERM with a custom message

# Define a SIGTERM trap
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
