#!/usr/bin/env bash
# This script stops the 7-highlander process by sending SIGTERM

# shellcheck disable=SC2009
# Find the PID of 7-highlander
pid=$(ps -ef | grep "[7]-highlander" | awk '{print $2}')

# Send SIGTERM to the PID
if [ -n "$pid" ]; then
    kill -15 "$pid"
fi
